### ISSUE TITLE
Создание презентации

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#16]
Слайды (пока очень примерно)
1.  Название органзиации + лого
2.  Мб какое-то краткое втупление/описание организации
3.  Описание проблемы ("боль" заказчика)
4.  Введение в проблематику
5.  Представление нашего решения
6.  Архитектура решения
7.  О средствах, которые мы используем 
8.  Что-то юридическое мб
9.  Завершение

**Comment by Lanavin** [comment]
вот тут промежуточная презентация
https://docs.google.com/presentation/d/1c3lO1p2X3cPgeL_wnpM6GUjGen1gFDA2LJDZP-xYr5Q/edit?usp=sharing
