### ISSUE TITLE
Материалы для презентации

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#17]
Отдельная задача - сюда кидать все материалы для презентации

**Comment by IvanGluhof** [comment]
Был на конференции Oracle. Сфоткал интересные слайды, с хорошим оформлением и идеями. Может, пригодиться 
![IMG_20191030_112835](https://user-images.githubusercontent.com/55379654/67978710-c88d2f80-fc2b-11e9-9393-9d2f9365d9a6.jpg)
![IMG_20191030_114025](https://user-images.githubusercontent.com/55379654/67978711-c88d2f80-fc2b-11e9-9a0f-5a93f4e166a5.jpg)
![IMG_20191030_114454](https://user-images.githubusercontent.com/55379654/67978712-c88d2f80-fc2b-11e9-9105-92a3bc79d08b.jpg)
![IMG_20191030_114837](https://user-images.githubusercontent.com/55379654/67978714-c925c600-fc2b-11e9-8655-0bea06c61e4a.jpg)
![IMG_20191030_115224](https://user-images.githubusercontent.com/55379654/67978715-c925c600-fc2b-11e9-9e19-eadd3f7ee762.jpg)
![IMG_20191030_120513](https://user-images.githubusercontent.com/55379654/67978716-c925c600-fc2b-11e9-80f0-7879fe73781c.jpg)
![IMG_20191030_121942](https://user-images.githubusercontent.com/55379654/67978719-c9be5c80-fc2b-11e9-9e1d-b8486a614aac.jpg)
![IMG_20191030_122629](https://user-images.githubusercontent.com/55379654/67978720-c9be5c80-fc2b-11e9-84ed-c7492c388af1.jpg)
![IMG_20191030_123000](https://user-images.githubusercontent.com/55379654/67978721-c9be5c80-fc2b-11e9-97aa-43b9b35a1437.jpg)
![IMG_20191030_123155](https://user-images.githubusercontent.com/55379654/67978722-ca56f300-fc2b-11e9-8070-ec6b1efbfefa.jpg)

**Comment by Thunderbird1** [comment]
![возможности](https://user-images.githubusercontent.com/24624012/68384602-fcef7700-0168-11ea-99e6-6782862f6de8.png)

**Comment by Thunderbird1** [comment]
![image_2019-11-07_13-14-26](https://user-images.githubusercontent.com/24624012/68384626-0842a280-0169-11ea-8d27-21f2dddd5142.png)

**Comment by IvanGluhof** [comment]
Несколько важных слайдов по инфраструктуре облака
Без дизайна, чтобы можно было переносить
[PD_cloud_concept1_ekb.pptx](https://github.com/SimplexSolution/NERO_Production/files/3824727/PD_cloud_concept1_ekb.pptx)
