### ISSUE TITLE
Презентация 

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#18]
Итоговый вариант by @sbuzhgeev 
[Презентация.pdf](https://github.com/SimplexSolution/NERO_Production/files/3825751/default.pdf)
[Презентация.pptx](https://github.com/SimplexSolution/NERO_Production/files/3825752/default.pptx)

Чуть подрихтовал
[Презентация.pptx](https://github.com/SimplexSolution/NERO_Production/files/3826318/default.pptx)

Подрихтовал
[Презентация.pptx](https://github.com/SimplexSolution/NERO_Production/files/3826372/default.pptx)

**Comment by Lanavin** [comment]
Промежуточная презентация 
https://docs.google.com/presentation/d/1c3lO1p2X3cPgeL_wnpM6GUjGen1gFDA2LJDZP-xYr5Q/edit?usp=sharing

@sbuzhgeev  добавь свою версию презентации, чтобы ребята видели

**Comment by IvanGluhof** [comment]
> 
> 
> Промежуточная презентация
> https://docs.google.com/presentation/d/1c3lO1p2X3cPgeL_wnpM6GUjGen1gFDA2LJDZP-xYr5Q/edit?usp=sharing
> 
> @sbuzhgeev добавь свою версию презентации, чтобы ребята видели

Очень даже, well done

**Comment by sbuzhgeev** [comment]
https://docs.google.com/presentation/d/1Yb9htg4ZFh0Oc2u1Euimme2Hw0YIKxnEMvs2cNo_0wA/edit?usp=sharing

**Comment by IvanGluhof** [comment]
> https://towardsdatascience.com/a-review-of-named-entity-recognition-ner-using-automatic-summarization-of-resumes-5248a75de175

Выглядит конечно круто, но масштабность задачи - слишком громко) Лучше описывать как сложную, комплексную задачу. О масштабе пока в принципе речи не идёт

**Comment by Thunderbird1** [comment]
[слайд о датасетах.pptx](https://github.com/SimplexSolution/NERO_Production/files/3819266/default.pptx)

**Comment by IvanGluhof** [comment]
Схема нашего решения
[solutions_schema.zip](https://github.com/SimplexSolution/NERO_Production/files/3824417/solutions_schema.zip)
