### ISSUE TITLE
Анализ в части data science

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#29]
* Первичный анализ от Виктора [analysys.txt](https://github.com/SimplexSolution/NERO_Production/files/3795053/analysys.txt)
* [Размеченный под NER датасет](https://www.kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-etities)

Вопросы:

- Признаки при построении деревьев - некий критерий, позволяющий расщепить далее на ветви. Каким образом он случайно устанавливается в деревьях случайного леса?
- Нужно ли знать, как именно производится обучение на решающих деревьях? Чтобы разобраться в  machinelearning.ru/wiki/images/a/a5/MOTP14_8.pdf необходима помощь  
- Что такое "сложность" в случае построения и ветвления деревьев? Со точностью понятно (скажем, точность разделения цветов на картинке)
- По последнему слайду тоже бы пару комментариев
- Вдогонку - критерий расщепления - это формализованный "признак"? То есть признак с выставленными условиями, куда двигаться в каком случае

**Comment by IvanGluhof** [comment]
- Вдогонку - критерий расщепления - это формализованный "признак"? То есть признак с выставленными условиями, куда двигаться в каком случае - насколько я знаю - нет. В большинстве моделей этой конкретный критерий (например критерий Джини). Выбор критерия вообще зависи от модели, и в принципе все возможные критерии выбора есть в во всех ML моделях на сегодня

**Comment by IvanGluhof** [comment]
- По последнему слайду тоже бы пару комментариев - имеется в виду чем длиннее и "ветвистее" дерево, тем оно сложнее. Добавление новых ветвей не всегда значит, что будет что-то лучше, а скорее усложнит

**Comment by IvanGluhof** [comment]
- Что такое "сложность" в случае построения и ветвления деревьев? Со точностью понятно (скажем, точность разделения цветов на картинке) - это глубина дерева

**Comment by IvanGluhof** [comment]
- Признаки при построении деревьев - некий критерий, позволяющий расщепить далее на ветви. Каким образом он случайно устанавливается в деревьях случайного леса? - ох, вообще это дикая математика. На данный момент не особо важно, как он устанавливается. Как я писал выше, почти все ML модели на сегодня имеется все необходимые критерии. 
[Вот здесь](https://dyakonov.org/2016/11/14/%D1%81%D0%BB%D1%83%D1%87%D0%B0%D0%B9%D0%BD%D1%8B%D0%B9-%D0%BB%D0%B5%D1%81-random-forest/) и [здесь](https://habr.com/ru/post/320726/) неплохо и довольно просто расписано.

**Comment by IvanGluhof** [comment]
- Нужно ли знать, как именно производится обучение на решающих деревьях? Чтобы разобраться в machinelearning.ru/wiki/images/a/a5/MOTP14_8.pdf необходима помощь - и да и нет. Это довольно сложная математика, особенно в глубоких деревьях, но поверхностно знать и понимать желательно. Ссылки в предыдущем комменте

**Comment by Thunderbird1** [comment]
Kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-entities

Размеченный под NER датасет

**Comment by IvanGluhof** [comment]
> 
> 
> Kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-entities
> 
> Размеченный под NER датасет

Выдаёт 404

**Comment by Thunderbird1** [comment]
> > Kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-entities
> > Размеченный под NER датасет
> 
> Выдаёт 404

https://www.kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-etities

**Comment by IvanGluhof** [comment]
> 
> 
> > > Kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-entities
> > > Размеченный под NER датасет
> > 
> > 
> > Выдаёт 404
> 
> https://www.kaggle.com/abhinavwalia95/chemdner-iob-annotated-chemical-named-etities

Можешь кстати в wiki добавить эту ссылку

**Comment by Thunderbird1** [comment]
Ок

**Comment by Thunderbird1** [comment]
http://www.nactem.ac.uk/tsujii/GENIA/ERtask/report.html
https://www.kaggle.com/dataturks/best-buy-ecommerce-ner-dataset/home
https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus
https://www.kaggle.com/snap/amazon-fine-food-reviews
https://www.kaggle.com/fredgirod/web-crawler-for-real-estate-market

**Comment by IvanGluhof** [comment]
> 
> 
> http://www.nactem.ac.uk/tsujii/GENIA/ERtask/report.html
> https://www.kaggle.com/dataturks/best-buy-ecommerce-ner-dataset/home
> https://www.kaggle.com/abhinavwalia95/entity-annotated-corpus
> https://www.kaggle.com/snap/amazon-fine-food-reviews
> https://www.kaggle.com/fredgirod/web-crawler-for-real-estate-market

Вторую ссылку пофикси

**Comment by IvanGluhof** [comment]
По дата сетам пока хватит. Перевожу на ревью

Потом оформлю связный тикет по использованию текущих дата сетов
