### ISSUE TITLE
Анализ практического применения

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#3]
#### Как сервисы, инструменты
1. Ответы на часто задаваемые вопросы (FAQ), deep learning question-answering system
2. dialog systems - диалоговые системы
3. Чат боты 
4. Customer Service в принципе - пожалуй, наиболее финансово выгодное применение

@Thunderbird1 icml.sberbank.ai - возможно, сбербанк павловым пользуется

Особо узнать как конкретно используют DP не удалось. Вот [список](http://ipavlov.ai/ru#popup:myform2) тех, кто точно использует у себя в системе:
- facebook
- nvidia
- Сбербанк
- yandex
- samsung
- fastlaw.io
- AutoFAQ.ai
- DataMonsters
- Just AI
- Европейская Юридическая Служба
- IT Expert
- Arni
- Автоответчик 24/7
- Salebot

**Comment by Thunderbird1** [comment]
icml.sberbank.ai - возможно, сбербанк павловым пользуется
