### ISSUE TITLE
Брошюра/Intro

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#35]
Брошюра для быстрого ознакомления с:
1) Командой (компанией)
2) Задачей
3) Проектом

**Comment by IvanGluhof** [comment]
На дворе 21й век, будем брать из шаболнов Word

Что мне понравилось:
- https://templates.office.com/en-us/software-brochure-tm00591095
- https://templates.office.com/en-us/modern-brochure-tm16412252
- https://templates.office.com/en-us/tri-fold-business-brochure-black-red-design-tm00001093
- https://templates.office.com/en-us/company-brochure-tm02933472

**Comment by Lanavin** [comment]
http://maketron.ru/editor?#editortemplateid=2443

**Comment by IvanGluhof** [comment]
Вот что получилось:
[SimplexSolutions_AboutUs.docx](https://github.com/SimplexSolution/NERO_Production/files/3816793/SimplexSolutions_AboutUs.docx)
[SimplexSolutions_AboutUs.pdf](https://github.com/SimplexSolution/NERO_Production/files/3816794/SimplexSolutions_AboutUs.pdf)

Перевожу на ревью
