### ISSUE TITLE
Название организации/стартапа

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#36]
Красивое и лаконичное название нашей славной организации

**Comment by IvanGluhof** [comment]
Simplex Solutions - вообще первое, что пришло мне в голову. Хотел что-то на подобии Brilliant Software (по работе знаком), но получилось Simplex Solutions.
Ни за ни против никто не высказался - оставляем?

**Comment by IvanGluhof** [comment]
@sbuzhgeev Саян, что скажешь?
@Lanavin интересует мнение как маркетолога в первую очередь

**Comment by Lanavin** [comment]
А мне и NERO понравилось

**Comment by IvanGluhof** [comment]
> 
> 
> А мне и NERO понравилось

Ну NERO это вроде как название инструмента. Но можно продумать и с NERO - могешь?

**Comment by Lanavin** [comment]
у меня ассоциации с небом (наше облако) + горы (simplex - треугольник) +

**Comment by IvanGluhof** [comment]
> 
> 
> у меня ассоциации с небом (наше облако) + горы (simplex - треугольник) +

Попробуй сделать тогда такой логотип

**Comment by sbuzhgeev** [comment]
по-моему, Сиплекс вполне отражает харакетр нашего проекта - мы упрощаем поиск, ускоряем процессы в компании тем самым, поэтому Симплекс - оно самое.

**Comment by IvanGluhof** [comment]
Тогда оставляем
