### ISSUE TITLE
Анализ областей применения

### ISSUE THREAD

**Issue by IvanGluhof** [SimplexSolution/NERO_Production#4]
Основная задача DP: Поиск именованных сущностей (Named Entity Recognition — NER) — частная задача  извлечения информации, состоит в поиске именованных сущностей в слабоструктурированных текстах (как правило на естественных языках).

Именованная сущность — имя предмета или явления. Например: имена людей, организаций, событий, мест (географических и политических); дат и др. 
#### Области применения
1. NLP - Natural Language Processing
2. Text understating (понимание текста, контекста)
3. Генерация текста (на основе какой-то выборки)
4. Intent recognition - распознования "намерения". По контексту 

Связано с #3.

**Comment by Thunderbird1** [comment]
Pdfa.semanricscholat.org/ad82/20d886e9bd649ec2a9a25f9c187d73ff285c.pdf

**Comment by Thunderbird1** [comment]
![возможности](https://user-images.githubusercontent.com/24624012/68384537-dcbfb800-0168-11ea-96be-bf3bdab6bd28.png)
